# Generated by Django 5.2.13 on 2026-04-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='alerts/'),
        ),
    ]
