# Generated by Django 5.2.13 on 2026-05-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alertlog_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.IntegerField(default=102)),
                ('process_frame_rate', models.IntegerField(default=10, help_text='Process every Nth frame')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
