# Generated by Django 5.2.13 on 2026-05-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_cameradevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='distance_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
