# Generated by Django 5.2.13 on 2026-05-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alertlog_distance_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='likely_candidate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
