# Generated by Django 5.2.13 on 2026-05-15 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alertlog_likely_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='NVRDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=554)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RTSPStringTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template_string', models.TextField(help_text='Use placeholders: {user}, {password}, {ip}, {port}, {channel}')),
            ],
        ),
        migrations.AlterField(
            model_name='cameradevice',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cameradevice',
            name='nvr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='dashboard.nvrdevice'),
        ),
        migrations.AddField(
            model_name='nvrdevice',
            name='rtsp_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.rtspstringtemplate'),
        ),
    ]
