# Generated by Django 5.2.13 on 2026-05-19 07:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_nvrdevice_rtspstringtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtspstringtemplate',
            name='template_string',
            field=models.TextField(help_text='Provide the path/query suffix. Use placeholder: {channel}'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='dashboard.employee')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
