# Generated by Django 5.2.13 on 2026-05-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_rtspstringtemplate_template_string_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_open_time', models.TimeField(default='09:00:00')),
                ('office_close_time', models.TimeField(default='18:00:00')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='On Time', max_length=100),
        ),
    ]
